# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9809f834e1886c0698f13e6c481a7a3c74f105131e06e4f5d9e49e86645cb7190d7a89de75f8a07dda1991a50958a0c67859db465c6d7394cdf07a6c1cc334a

test:
  secret_key_base: a97a5ddce2529cf68aa0a3400f4e06967efc8bbb9a2557415ddc306592e9caf68d835874d67993d1675c83e8db2ee247c364cf54efeec7531eca713dd4066db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
