class AddAllFieldsToGames < ActiveRecord::Migration
  def change
    add_column :games, :barracks_killed, :integer
    add_column :games, :combat_player_score, :integer
    add_column :games, :consumables_purchased, :integer
    add_column :games, :damage_dealt_player, :integer
    add_column :games, :double_kills, :integer
    add_column :games, :first_blood, :integer
    add_column :games, :gold, :integer
    add_column :games, :gold_earned, :integer
    add_column :games, :gold_spent, :integer
    add_column :games, :item0, :integer
    add_column :games, :item1, :integer
    add_column :games, :item2, :integer
    add_column :games, :item3, :integer
    add_column :games, :item4, :integer
    add_column :games, :item5, :integer
    add_column :games, :item6, :integer
    add_column :games, :items_purchased, :integer
    add_column :games, :largest_critical_strike, :integer
    add_column :games, :largest_killing_spree, :integer
    add_column :games, :largest_multi_kill, :integer
    add_column :games, :legedary_items_created, :integer
    add_column :games, :level, :integer
    add_column :games, :magic_damage_dealt_player, :integer
    add_column :games, :magic_damage_dealt_to_champions, :integer
    add_column :games, :magic_damage_taken, :integer
    add_column :games, :minions_denied, :integer
    add_column :games, :neutral_minions_killed, :integer
    add_column :games, :neutral_minions_killed_enemy_jungle, :integer
    add_column :games, :neutral_minions_killed_your_jungle, :integer
    add_column :games, :nexus_killed, :boolean
    add_column :games, :node_capture, :integer
    add_column :games, :node_capture_assist, :integer
    add_column :games, :node_neutralize, :integer
    add_column :games, :node_neutralize_assist, :integer
    add_column :games, :num_items_bought, :integer
    add_column :games, :objective_player_score, :integer
    add_column :games, :penta_kills, :integer
    add_column :games, :physical_damage_dealt_player, :integer
    add_column :games, :physical_damage_dealt_to_champions, :integer
    add_column :games, :physical_damage_taken, :integer
    add_column :games, :player_position, :integer
    add_column :games, :player_role, :integer
    add_column :games, :quadra_kills, :integer
    add_column :games, :sight_wards_bought, :integer
    add_column :games, :spell_1_cast, :integer
    add_column :games, :spell_2_cast, :integer
    add_column :games, :spell_3_cast, :integer
    add_column :games, :spell_4_cast, :integer
    add_column :games, :summon_spell_1_cast, :integer
    add_column :games, :summon_spell_2_cast, :integer
    add_column :games, :super_monster_killed, :integer
    add_column :games, :team, :integer
    add_column :games, :team_objective, :integer
    add_column :games, :time_player, :integer
    add_column :games, :total_heal, :integer
    add_column :games, :total_player_score, :integer
    add_column :games, :total_score_rank, :integer
    add_column :games, :total_time_crowd_control_dealt, :integer
    add_column :games, :total_units_healed, :integer
    add_column :games, :triple_kills, :integer
    add_column :games, :true_damage_dealt_player, :integer
    add_column :games, :true_damage_dealt_to_champions, :integer
    add_column :games, :true_damage_taken, :integer
    add_column :games, :turrets_killed, :integer
    add_column :games, :unreal_kills, :integer
    add_column :games, :victory_point_total, :integer
    add_column :games, :vision_wards_bought, :integer
    add_column :games, :ward_killed, :integer
    add_column :games, :ward_placed, :integer
  end
end
